"""Governed semantic retrieval for collective memories.

Phase 8B:
- returns scored semantic results rather than bare IDs
- enforces collective lifecycle authorization
- validates query and stored embeddings
- preserves provenance
- provides deterministic ordering
- supports source-profile filtering

The collective database remains authoritative. Embeddings are treated as
opaque float32 vectors generated by the project's embedding backend.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Iterable, Sequence

import numpy as np

from src.domain.collective import CollectiveDAO
from src.domain.embedding_generator import DEFAULT_DIMENSIONS, decode_embedding


@dataclass(frozen=True)
class SemanticResult:
    """A governed semantic retrieval result."""

    entry_id: int
    source_profile: str
    origin_memory_id: str
    semantic_score: float
    provenance: tuple


class SemanticSearcher:
    """Perform governed semantic retrieval over collective embeddings."""

    def __init__(self, dao: CollectiveDAO | None = None) -> None:
        self._dao = dao or CollectiveDAO()
        self._dao.ensure_schema()

    @staticmethod
    def _validate_query(vector: Sequence[float] | Iterable[float]) -> np.ndarray:
        try:
            values = [float(value) for value in vector]
        except (TypeError, ValueError):
            raise ValueError("query embedding must contain numeric values")

        if len(values) != DEFAULT_DIMENSIONS:
            raise ValueError(
                f"query embedding must contain exactly "
                f"{DEFAULT_DIMENSIONS} dimensions"
            )

        array = np.asarray(values, dtype=np.float32)

        if not np.all(np.isfinite(array)):
            raise ValueError("query embedding must contain only finite values")

        norm = float(np.linalg.norm(array))
        if not math.isfinite(norm) or norm == 0.0:
            raise ValueError("query embedding must have a non-zero norm")

        return array / norm

    @staticmethod
    def _decode_candidate(blob) -> np.ndarray | None:
        try:
            vector = decode_embedding(blob)
        except (TypeError, ValueError):
            return None

        array = np.asarray(vector, dtype=np.float32)

        if len(array) != DEFAULT_DIMENSIONS:
            return None

        if not np.all(np.isfinite(array)):
            return None

        norm = float(np.linalg.norm(array))
        if not math.isfinite(norm) or norm == 0.0:
            return None

        return array / norm

    def search(
        self,
        vector: Sequence[float] | Iterable[float],
        top_k: int = 10,
        profile: str | None = None,
    ) -> list[SemanticResult]:
        """Return governed semantic matches ordered by score then entry ID."""

        if not isinstance(top_k, int) or isinstance(top_k, bool) or top_k < 1:
            raise ValueError("top_k must be a positive integer")

        query = self._validate_query(vector)

        sql = """
            SELECT
                id,
                source_profile,
                origin_memory_id,
                embedding
            FROM collective_entries
            WHERE is_promoted = 1
              AND is_revoked = 0
              AND embedding IS NOT NULL
        """
        params: list[object] = []

        if profile is not None:
            sql += " AND source_profile = ?"
            params.append(str(profile))

        sql += " ORDER BY id ASC"

        candidates = []

        for row in self._dao.conn.execute(sql, params):
            candidate = self._decode_candidate(row["embedding"])
            if candidate is None:
                continue

            score = float(np.dot(query, candidate))

            if not math.isfinite(score):
                continue

            candidates.append(
                (
                    score,
                    int(row["id"]),
                    str(row["source_profile"]),
                    str(row["origin_memory_id"]),
                )
            )

        candidates.sort(key=lambda item: (-item[0], item[1]))

        results: list[SemanticResult] = []

        for score, entry_id, source_profile, origin_memory_id in candidates[:top_k]:
            provenance_rows = self._dao.get_provenance(entry_id)
            provenance = tuple(
                (
                    row["source_profile"],
                    row["origin_memory_id"],
                    row["created_at"],
                )
                for row in provenance_rows
            )

            results.append(
                SemanticResult(
                    entry_id=entry_id,
                    source_profile=source_profile,
                    origin_memory_id=origin_memory_id,
                    semantic_score=score,
                    provenance=provenance,
                )
            )

        return results
